baseurl = "https://www.example.com"
title = "My New Product"
author = "Ricardo N Feliciano (FelicianoTech)"
canonifyurls = true
paginate = 3

theme = "hugo-theme-lean-launch-page"

googleAnalytics = "UA-123456"

[params]
tagline = "We're launching a new, better solution."
mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"

twitter = "https://twitter.com/MyNewProduct"
facebook = "https://facebook.com/MyNewProduct"
instagram = "https://instragram.com/MyNewProduct"
googleplus = "https://plus.google.com/+MyNewProduct"
